ftp:
  package_name: vsftpd
  package_version: 3.0.2-9.el7
  service_name: vsftpd
dhcp:
  package_name: dhcp
  package_version: 4.2.5
  service_name: dhcpd
apache:
  package_name: httpd
  package_version: 2.4.6
  service_name: httpd
