---
# file: site.yml
- hosts: all
  roles:
    - base
  sudo: True
  vars_files:
    - "group_vars/default.yml" 
    - "group_vars/{{ ansible_os_family }}.yml"

- hosts: server1
  roles:
    - server1
  sudo: True
  vars_files:
    - "group_vars/default.yml" 
    - "group_vars/{{ ansible_os_family }}.yml"

- hosts: icinga
  roles:
    - icinga
  sudo: True
  vars_files:
    - "group_vars/default.yml" 
    - "group_vars/{{ ansible_os_family }}.yml"

- hosts: tracgit
  roles:
    - tracgit
  sudo: True
  vars_files:
    - "group_vars/default.yml"
    - "group_vars/{{ansible_os_family }}.yml"