---
# Main configuration file
- hosts: all
  roles:
    - base
  become_method: sudo
  vars_files:
    - "group_vars/default.yml"
    - "group_vars/ethnalaya.yml"
    - "group_vars/{{ansible_os_family}}.yml"
