---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  ansible_verbose: false
  roles_path: ../../roles

verifier:
  name: serverspec

platforms:
  - name: centos-core
    driver_config: 
      box: centos72
      network:
        - ['forwarded_port', {guest: 8080, host: 8080}]
      

  - name: centos-final
    driver_config: 
      box: centos67

suites:
  - name: default

