---
- name: start nginx
  service: name={{nginx.service_name}} state=started
  tags: nginx-service

- name: stop nginx
  service: name={{nginx.service_name}} state=stopped
  tags: nginx-service

- name: restart nginx
  service: name={{nginx.service_name}} state=restarted
  tags: nginx-service

- name: reload nginx
  service: name={{nginx.service_name}} state=reloaded
  tags: nginx-service

- name: enable nginx
  service: name={{nginx.service_name}} state=started enabled=yes
  tags: nginx-service

- name: disable nginx
  service: name={{nginx.service_name}} state=stopped enabled=no
  tags: nginx-service