---
- name: update firewalld settings - Jenkins port
  firewalld: port="{{jenkins.firewalld_service_port}}/{{jenkins.firewalld_service_protocol}}"
    zone="{{firewall_zone}}"
    permanent=true immediate=true
    state=enabled
  when: ansible_os_family == 'RedHat' and {{ansible_distribution_major_version}} >=7 and {{firewall_enabled}}

- name: update firewalld settings - Jenkins service
  firewalld: service="{{jenkins.firewalld_service_name}}"
    zone="{{firewall_zone}}"
    permanent=true immediate=true
    state=enabled
  when: ansible_os_family == 'RedHat' and {{ansible_distribution_major_version}} >=7 and {{firewall_enabled}}

- name: Toogle SE Linux Boolean value for accessing Jenkins
  seboolean:  name={{item}}
    state=yes
    persistent=yes
  when: ansible_os_family == 'RedHat'
  with_items:
    - httpd_can_network_relay
    - httpd_can_network_connect

- name: Update Jenkins log rotate
  template: src=jenkins.j2
    dest=/etc/logrotate.d/jenkins
    owner=root group=root
- name: Update Nginx Reverse proxy configurations
  template: src=jenkins.conf.j2
    dest={{nginx.conf_directory}}/jenkins.conf
    owner=root group=root
  notify: reload nginx