---
- name: update firewalld settings - Jenkins port
  firewalld: port="{{jenkins.firewalld_service_port}}/{{jenkins.firewalld_service_protocol}}" zone="{{firewall_zone}}"
             permanent=true immediate=true
             state=enabled
  when: ansible_os_family == 'RedHat' and {{ansible_distribution_major_version}} >=7 and {{firewall_enabled}}
  tags: jenkins-configure,firewall-configure

- name: update firewalld settings - Jenkins service
  firewalld:  service="{{jenkins.firewalld_service_name}}" zone="{{firewall_zone}}"
              permanent=true immediate=true
              state=enabled
  when: ansible_os_family == 'RedHat' and {{ansible_distribution_major_version}} >=7 and {{firewall_enabled}}
  tags: jenkins-configure,firewall-configure
