---
- name: install dnsmasq package 
  action: "{{ ansible_pkg_mgr }} pkg=dnsmasq state=present"
  notify:
    - start dnsmasq
  tags: dnsmasq-package

- name: enable dnsmasq service
  service: name=dnsmasq enabled=true
  tags: dnsmasq-confs
  
- name: update dnsmasq configurations
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf force=yes
  notify:
    - restart dnsmasq
  tags: dnsmasq-confs

- name: update dns ports
  firewalld: "service={{item}} permanent=true zone={{ firewall_zone}} state=enabled"
  with_items:
    - dns
    - dhcp
  when: ansible_os_family == 'RedHat'
  tags: dnsmasq-confs