---
- name: install ntp package
  action: "{{ ansible_pkg_mgr }} pkg={{ ntp.package_name }}-{{ ntp.package_version }} state=present"
  notify:
    - start ntp
  tags: ntps-package

- name: enable ntp service
  service: "name={{ntp.service_name}} enabled=true"
  tags: ntps-service
  
- name: update ntp-server configurations
  template: src=ntp.conf.j2 dest=/etc/ntp.conf force=yes
  notify:
    - restart ntp
  tags: ntps-confs

- name: update firewall settings 
  firewalld: "service=ntp permanent=true zone={{ firewall_zone}} state=enabled"
  when: ansible_os_family == 'RedHat'
  tags: ntps-confs