---
- name: Include variables
  include_vars: "{{ item }}"
  with_items:
    - main.yml
    - "{{ansible_os_family}}.yml"
    - "{{ansible_distribution}}-{{ansible_distribution_version}}.yml"
- block:
  - name: Install ansible client essential packages
    package: name=libselinux-python
      state=present

  - include: repos.yml

  when: ansible_os_family == 'RedHat'

  rescue:
    - name: Error Message
      debug: msg='ERROR => Setup failed'

- include: ntp_client.yml
