---
- name: Include variable set
  include_vars: "{{ item }}"
  with_items:
    - main.yml
    - "{{ansible_os_family}}.yml"
    - "{{ ansible_distribution }}-{{ansible_distribution_version}}.yml"

- include: ntp_client.yml
