---

- name: create .ssh directory
  file: "dest={{ home_dir }}/.ssh state=directory owner={{ user_name }} group={{ group_name }} mode=0700"
  tags: remote-ssh
  
- name: update authorized_keys 
  authorized_key: user={{ user_name }} key="{{ item }}"
  with_file:
    - controlmaster.pub
  tags: remote-ssh
  
- name : update permissions
  file: "dest={{ home_dir }}/.ssh/authorized_keys owner={{ user_name }} group={{ group_name }} mode=0600"
  tags: remote-ssh
  
- name: update sudoers for with no password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
  when: ansible_os_family == 'RedHat'
  tags: remote-ssh
  
- name: ssh firewall settings
  firewalld: "service=ssh permanent=true zone={{ firewall_zone }} state=enabled"
  when: ansible_os_family == 'RedHat'
  tags: remote-ssh

- name: update sudoers for with no password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
  tags: remote-ssh
  when: ansible_os_family == 'Debian'
 