---
- name: update firewalld settings
  firewalld:  service="{{vsftpd.firewalld_service_name}}"
    zone="{{firewall_zone}}"
    permanent=true immediate=true
    state=enabled
  when: ansible_os_family == 'RedHat' and {{ansible_distribution_major_version}} >=7 and {{firewall_enabled}}

- name: create directory structure
  file: path="{{vsftpd.base_directory}}/{{item}}"
    state=directory
  become_user: sudo
  with_items:
    - kickstart
    - repos
    - CentOS/6.6
    - CentOS/7.2.1511

- name: update vsftpd configuration
  template: src=vsftpd.conf.j2
    dest={{vsftpd.conf_file}}
    owner={{vsftpd.service_owner}}
    group={{vsftpd.service_group}}
    mode="0600"
  notify: restart vsftpd